# Generated by Django 3.2.4 on 2021-07-14 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='subject',
            field=models.CharField(blank=True, choices=[('Physics', 'Physics'), ('Chemistry', 'Chemistry'), ('Computer Science', 'Computer Science'), ('Maths', 'Maths'), ('English', 'English')], default='Physics', max_length=100),
        ),
    ]
