# Generated by Django 3.2.4 on 2021-08-22 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0007_question'),
    ]

    operations = [
        migrations.CreateModel(
            name='Qbank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(max_length=500)),
                ('choice1', models.TextField(max_length=200)),
                ('choice2', models.TextField(max_length=200)),
                ('choice3', models.TextField(max_length=200)),
                ('choice4', models.TextField(max_length=200)),
                ('answer', models.CharField(max_length=1)),
            ],
        ),
    ]
